### PR TITLE
fix: Apply filenamePattern setting when saving notes

### LINKED ISSUE #71: Bug: filenamePattern setting is ignored when saving notes
## Description

The `filenamePattern` setting (e.g., `{date}-{title}`) is not being applied when saving individual note files. Notes are always saved with just the title as the filename, regardless of the configured pattern.

## Steps to Reproduce

1. Go to plugin settings
2. Set "Save notes as" to "Individual files"
3. Set "Filename pattern" to `{date}-{title}`
4. Run a sync
5. Observe that files are created with just the title (e.g., `Meeting Name.md` instead of `2024-12-30-Meeting Name.md`)

## Root Cause

In `src/services/documentProcessor.ts`, the `prepareNote()` method generates the filename as:

```typescript
const filename = sanitizeFilename(title) + ".md";  // Line 72
```

This ignores the `filenamePattern` setting entirely. The same issue exists in `prepareCombinedNote()` (line 149) and `prepareTranscript()` (line 89).

While `PathResolver.computeNotePath()` correctly uses `resolveFilenamePattern()`, the `DocumentProcessor` doesn't use it when generating filenames.

## Expected Behavior

Files should be named according to the configured `filenamePattern`, applying all supported variables (`{title}`, `{date}`, `{time}`, `{year}`, `{month}`, `{day}`).

## Suggested Fix

Pass `NoteSettings` (including `filenamePattern`) and the note date to `DocumentProcessor`, then use `resolveFilenamePattern()` from `filenameUtils.ts` to generate the filename.

### PR DESCRIPTION
**Pull request by ejester-gusto**
## Summary

Fixes #71 - The `filenamePattern` setting was being ignored when saving notes.

- Notes were always saved with just the title (e.g., `Meeting Name.md`) regardless of the configured pattern
- Now respects patterns like `{date}-{title}` producing `2024-12-30-Meeting Name.md`

## Changes

- Added `DocumentProcessorSettings` interface with `filenamePattern` and `transcriptFilenamePattern`
- Added `generateFilename()` helper method to `DocumentProcessor`
- Updated `prepareNote`, `prepareCombinedNote`, and `prepareTranscript` to use pattern-based filename generation
- Updated `main.ts` to pass filename patterns to `DocumentProcessor`
- Added tests for filename pattern functionality

## Test plan

- [x] Added unit tests for filenamePattern in notes
- [x] Added unit tests for transcriptFilenamePattern in transcripts  
- [x] All 240 tests pass
- [x] Build succeeds
- [ ] Manual testing with various filename patterns

### CODE REVIEW

File: src/services/documentProcessor.ts [hunk 1]
```diff
@@ -1,20 +1,49 @@
...
 
+  /**
+   * Generates a filename based on the configured pattern.
+   *
+   * @param title - The document title
+   * @param noteDate - The date of the note
+   * @param isTranscript - Whether this is a transcript file
+   * @returns The generated filename with .md extension
+   */
+  private generateFilename(
```
Comment (tomelliot) [inline src/services/documentProcessor.ts]: We have `utils/filenameUtils.ts` - that would be a better place for this function. Let's refactor `resolveFilenamePattern` to accept a `doc` and a `pattern`. That will keep the calling functions more DRY and keep things simpler.

There'll be a few places we'll need to propagate this same change (e.g. `computeTranscriptPath`, `computeNotePath`).

**Review by tomelliot — CHANGES_REQUESTED** [review]
Thanks for catching this and for the PR @ejester-gusto.

If you don't want to make the adjustments you can add me as a collaborator in your fork of the repo and I can make them.

**Comment by ejester-gusto** [comment]
Thanks for the feedback! I've made the requested changes:

- Added `resolveDocFilename(doc, pattern)` to `utils/filenameUtils.ts` - this is a convenience function that extracts title and date from the doc and calls `resolveFilenamePattern`
- Simplified `DocumentProcessor` to use the new function instead of having its own `generateFilename` method
- Added tests for `resolveDocFilename`

I kept `resolveFilenamePattern(pattern, title, noteDate)` as-is since `PathResolver` uses it with pre-extracted title/date values. Let me know if you'd prefer to refactor `PathResolver` as well to use the doc-based function.

**Review by tomelliot — APPROVED** [review]
